[languages]
rust = ["rustfmt"]
go = ["gofmt"]
lua = ["stylua -s -"]
python = ["black --fast -"]
javascript = ["prettierd --stdin-filepath ./placeholder.js"]
typescript = ["prettierd --stdin-filepath ./placeholder.ts"]
bash = ["shfmt"]
shell = ["shfmt"]
